# Generated by Django 5.2.9 on 2025-12-21 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('annee', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-annee', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_etudiant', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('moyenne_generale', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('classement', models.IntegerField(default=0, editable=False)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiants.promotion')),
            ],
            options={
                'ordering': ['-moyenne_generale', 'nom', 'prenom'],
                'unique_together': {('promotion', 'numero_etudiant')},
            },
        ),
    ]
