# Generated by Django 5.2.9 on 2025-12-18 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='EspacePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Matière')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('formateurs', models.ManyToManyField(blank=True, related_name='espaces_pedagogiques', to='espaces_pedagogiques.formateur', verbose_name='Formateurs')),
            ],
            options={
                'verbose_name': 'Espace pédagogique',
                'verbose_name_plural': 'Espaces pédagogiques',
                'ordering': ['matiere'],
            },
        ),
    ]
