# Generated by Django 5.2.9 on 2025-12-19 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Promotion 2024-2025, Master Informatique 2024, etc.', max_length=200, verbose_name='Nom de la promotion')),
                ('annee', models.IntegerField(help_text='Année de la promotion', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la promotion', null=True, verbose_name='Description')),
                ('date_debut', models.DateField(help_text='Date de début de la promotion', verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Date de fin de la promotion', verbose_name='Date de fin')),
                ('nombre_etudiants', models.PositiveIntegerField(default=0, help_text="Nombre d'étudiants dans cette promotion", verbose_name="Nombre d'étudiants")),
                ('active', models.BooleanField(default=True, help_text='Indique si la promotion est actuellement active', verbose_name='Active')),
                ('couleur', models.CharField(default='#6366f1', help_text='Couleur associée à la promotion (format hexadécimal)', max_length=7, verbose_name='Couleur')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-annee', '-date_creation'],
                'unique_together': {('nom', 'annee')},
            },
        ),
    ]
